version: '3.8'

services:
  # 1. Node.js Web Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    container_name: node-web
    restart: always
    ports:
      - "8000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=27017

  # 2. Database Service (MongoDB)
  db:
    image: mongo:latest
    container_name: node-mongo-db
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: